apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  selector:
    app: rabbit
  ports:
    - name: management
      protocol: TCP
      port: 9090
      targetPort: 15672
    - name: port-4370
      protocol: TCP
      port: 4370
      targetPort: 4370
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  type: ClusterIP